[theme]
background = "#241F31"
primary = "#F6F5F4"
secondary = "#C0BFBC"
title = "#1C71D8"
playing = "#1C71D8"
playing_selected = "#1ED760"
playing_bg = "#000000"
highlight = "#62A0EA"
highlight_bg = "#000000"
error = "#C0BFBC"
error_bg = "#C01C28"
statusbar = "#000000"
statusbar_progress = "#3584E4"
statusbar_bg = "#3584E4"
cmdline = "#CBFFDE"
cmdline_bg = "#5E5C64"
