# Set color palette
palette = "gnome"

# Main prompt formatting
format = """
$username\
$hostname\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
$line_break\
$directory\
$line_break\
$character"""

[username]
show_always = true
format = '[$user](yellow5)[@](brown5)'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style) '
style = "blue5"

[directory]
style = "blue3"
truncation_length = 150
truncation_symbol = '.../'

[cmd_duration]
format = "[$duration]($style) "
style = "orange5"

[character]
success_symbol = "[>](green5)"
error_symbol = "[>](red5)"
vimcmd_symbol = "[>](purple5)"

[git_branch]
format = "[ ]($style)[$branch]($style)"
style = "light3"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](red5) ($ahead_behind$stashed)]($style)"
style = "yellow5"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "red5"

# Defining the color palette
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.gnome]
blue1 = '#99c1f1'
blue2 = '#62a0ea'
blue3 = '#3584e4'
blue4 = '#1c71d8'
blue5 = '#1a5fb4'
green5 = '#26a269'
yellow5 = '#e5a50a'
orange5 = '#c64600'
red5 = '#a51d2d'
purple5 = '#613583'
brown5 = '#63452c'
light1 = '#ffffff'
light2 = '#f6f5f4'
light3 = '#deddda'
light4 = '#c0bfbc'
light5 = '#9a9996'
dark1 = '#77767b'
dark2 = '#5e5c64'
dark3 = '#3d3846'
dark4 = '#241f31'
dark5 = '#000000'

