# Set color palette
palette = "catppuccin_macchiato"

# Main prompt formatting
format = """
$username\
$hostname\
$directory\
$cmd_duration\
$line_break\
$character"""

[username]
show_always = true
format = '[$user](bold yellow)[@](bold green)'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style): '
style = "bold peach"

[directory]
style = "teal"
truncation_length = 6
truncation_symbol = '.../'

[cmd_duration]
format = "[$duration]($style) "
style = "pink"

[character]
success_symbol = "[ 󰁕](teal)"
error_symbol = "[  󰁕](red)"
vimcmd_symbol = "[  󰁕](purple)"


# Defining the color palette
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

# [git_branch]
# format = "[$branch]($style)"
# style = "bright-black"
# symbol = ""

# [git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
# style = "cyan"
# conflicted = "​"
# untracked = "​"
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
# stashed = "≡"

# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bright-black"

